### ISSUE TITLE
does it support repartition?

### ISSUE THREAD

**Issue by whaon** [fluent/fluent-plugin-kafka#128]
the partition num of kafka topic is 5,so the partition is : 0,1,2,3,4
but if I alter the partition num to 8,and then the partition is : 0,1,2,3,4,5,6,7

does the plugin can realize the partition num is 8 now?
does it send msg to partition 5,6,7?

**Comment by repeatedly** [comment]
I'm not sure because cluster information is handled by ruby-kafka.
If ruby-kafka can detect partition change from kafka cluster, ruby-kafka can refresh it.
But if kafka doesn't notify it to clients, client hard to detect such changes.
out_kafka_buffered caches ruby-kafka producers, so cluster info update is delayed until client gets error from kafka.

out_kafka2, this is experimental implemetation for v014, creates producer at each buffer flush, so it should use latest cluster info.

**Comment by whaon** [comment]
@repeatedly ths
