### ISSUE TITLE
Introduce managed routing for Kafka large messages

### ISSUE THREAD

**Issue by snowjunkie** [fluent/fluent-plugin-kafka#328]
The current method using max_send_limit_bytes traps the record and sends to the log, but after reviewing the original issue and the below comment: (I'd like to raise the request for this option, so we can actually manage the record in a flow and as such divert to an alternative output rather than just log).

We have a number of situations whereby we see a large message and we'd like an elegant method to catch those and pipe to a managed output (such as store).  The current method is less clear as we have to then go matching on this in a log.

It seems this below option would meet our needs:

Another way is using `router.emit_error_event` to rescue events by `@ERROR`.

_Originally posted by @repeatedly in https://github.com/fluent/fluent-plugin-kafka/pull/118#issuecomment-292280418_

**Comment by kkurten** [comment]
Any progress on this issue? Logging large events in general is problematic and can cause major issues. We recently had an incident where we received large number of big log events from badly configured client(s) and it killed Docker Daemon on multiple hosts because the Docker logging driver could not handle the huge log events. IMO big log events should not be logged at all, only the metadata (tag etc.). Separate output would be really nice for debugging purposes.
